### ISSUE TITLE
Open Web Ui not updating when port is changed

### ISSUE THREAD

**Issue by uniqueandy29** [hassio-addons/addon-shinobi#1] opened 2018-04-11 05:12 UTC
# Problem/Motivation
When changing the TCP port from 5000 to something else the Open Web Ui link doesn't update 

> (Why the issue was filed)

## Expected behavior
Link should be changing based on the port number used in the config
> (What you expected to happen)

## Actual behavior
Open Web Ui link hard coded with port 5000
> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes
Link should be changing based on the port number used in the config
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment] 2018-05-14 10:31
@uniqueandy29, sorry to say, but the issue woth the link "Open web UI" is not fixable.
This is a known limitation of Hass.io.

We are currently using 2 ports (http/https). At this time, there is no way to tell which one is used and signal Hass.io to change its behavior.

Duplicate of #2

**Closed as completed by frenck** 2018-05-14 10:31 UTC
Labels: Type: Bug, Closed: Known limitation, Closed: Duplicate
